/*
 * Copyright © 2012 http://io7m.com
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
 * IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

package com.io7m.jcanephora;

/**
 * Blend function specification.
 */

public enum BlendFunction
{
  BLEND_CONSTANT_ALPHA,
  BLEND_CONSTANT_COLOR,
  BLEND_DESTINATION_ALPHA,
  BLEND_DESTINATION_COLOR,
  BLEND_ONE,
  BLEND_ONE_MINUS_CONSTANT_ALPHA,
  BLEND_ONE_MINUS_CONSTANT_COLOR,
  BLEND_ONE_MINUS_DESTINATION_ALPHA,
  BLEND_ONE_MINUS_DESTINATION_COLOR,
  BLEND_ONE_MINUS_SOURCE_ALPHA,
  BLEND_ONE_MINUS_SOURCE_COLOR,
  BLEND_SOURCE_ALPHA,
  BLEND_SOURCE_ALPHA_SATURATE,
  BLEND_SOURCE_COLOR,
  BLEND_ZERO,
}
