package com.io7m.jcanephora;

/**
 * Blend function specification.
 */

public enum BlendFunction
{
  BLEND_CONSTANT_ALPHA,
  BLEND_CONSTANT_COLOR,
  BLEND_DESTINATION_ALPHA,
  BLEND_DESTINATION_COLOR,
  BLEND_ONE,
  BLEND_ONE_MINUS_CONSTANT_ALPHA,
  BLEND_ONE_MINUS_CONSTANT_COLOR,
  BLEND_ONE_MINUS_DESTINATION_ALPHA,
  BLEND_ONE_MINUS_DESTINATION_COLOR,
  BLEND_ONE_MINUS_SOURCE_ALPHA,
  BLEND_ONE_MINUS_SOURCE_COLOR,
  BLEND_SOURCE_ALPHA,
  BLEND_SOURCE_ALPHA_SATURATE,
  BLEND_SOURCE_COLOR,
  BLEND_ZERO,
}
