package com.io7m.jcanephora;

public enum LogicOperation
{
  LOGIC_CLEAR,
  LOGIC_SET,
  LOGIC_COPY,
  LOGIC_COPY_INVERTED,
  LOGIC_NO_OP,
  LOGIC_INVERT,
  LOGIC_AND,
  LOGIC_NAND,
  LOGIC_OR,
  LOGIC_NOR,
  LOGIC_XOR,
  LOGIC_EQUIV,
  LOGIC_AND_REVERSE,
  LOGIC_AND_INVERTED,
  LOGIC_OR_REVERSE,
  LOGIC_OR_INVERTED
}
